<?php
/**
 * Copyright (c) 2012-2017, MOKADEV SAS
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are not permitted without the express authorization of the author
 *
 * @category    Mokadev
 * @package     Mokadev_Hupilytics
 * @author      Mohamed Kaïd (contact@mokadev.com)
 * @copyright   Copyright (c) 2012-2017 MOKADEV SAS (https://www.mokadev.com)
 * @license     Proprietary - no redistribution without authorization
 *
 **/
?>
<?php
    /* @var Mokadev_Hupilytics_Block_Tracking $this */
    $lang = Mage::helper('core')->jsQuoteEscape($this->getCurrentLanguage());
?>
<script type="text/javascript">
    var _paq = _paq || [];
    (function() {
        var u = 'https://api.catchbox.hupi.io/v2/<?php echo Mage::helper('core')->jsQuoteEscape($this->getAccount()) ?>/hupilytics';
        _paq.push(['setTrackerUrl', u]);
        _paq.push(['setSiteId', <?php echo Mage::helper('core')->jsQuoteEscape($this->getSiteId()) ?>]);

        _paq.push(['setUserId', '<?php echo Mage::helper('core')->jsQuoteEscape($this->getUserId()) ?>']);

        function current_ts()
        {
            // needed for IE8 compat, see http://bit.ly/1NLevPT
            if (!Date.now) {
                Date.now = function() {
                    return new Date().getTime();
                }
            }
            return Math.floor(Date.now() / 1000);
        }

        // ! Required ! Our API needs the current timestamp for the page
        _paq.push(['setCustomVariable', 1, 'current_ts', current_ts(), 'page']);
        _paq.push(['setCustomVariable', 42, 'lang', '<?php echo $lang ?>', 'page']);

        var _hupiProductIds = [];
        var listItems = jQuery('.hupi-recommendation [data-product-id]');

        if (listItems.length) {

            listItems.each(function() {
                _hupiProductIds.push(jQuery(this).data('product-id'));
            });

            if (_hupiProductIds.length > 0) {
                _paq.push(['setCustomVariable', 40, 'products_recommendation', _hupiProductIds ,'page']);
            }
        }


        <?php echo $this->_getProductPageCode()?>

        <?php echo $this->_getCartTrackingCode()?>

        <?php echo $this->_getOrdersTrackingCode()?>

        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);

        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript';
        g.defer=true;
        g.async=true;
        g.src=u;
        s.parentNode.insertBefore(g,s);
    })();
</script>