<?php
/**
 * Copyright (c) 2012-2017, MOKADEV SAS
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are not permitted without the express authorization of the author
 *
 * @category    Mokadev
 * @package     Mokadev_Hupilytics
 * @author      Mohamed Kaïd (contact@mokadev.com)
 * @copyright   Copyright (c) 2012-2017 MOKADEV SAS (https://www.mokadev.com)
 * @license     Proprietary - no redistribution without authorization
 *
 **/
?>
<?php
/** @var Mokadev_Hupilytics_Block_Product $this */
?>
<?php if($this->getProductCollection() && $this->getProductCollection()->getSize()): ?>
    <?php $_columnCount = 4; ?>
<div class="section hupi-recommendation" data-endpoint="<?php echo $this->getEndpoint() ?>">
    <div class="box-collateral">
        <h2 class="section-title"><?php echo $this->__('You may be interested in the following items') ?></h2>
        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col" id="reco-<?php echo $this->getEndpoint() ?>-product-table" data-recommendation="<?php echo $this->getEndpoint() ?>">
            <?php foreach ($this->getProductCollection()->getItems() as $_product): ?>
                <li data-product-id="<?php echo $_product->getId() ?>" data-product-name="<?php echo $this->jsQuoteEscape($this->escapeHtml($_product->getName())) ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                    </a>
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h3>
                    <?php echo $this->getPriceHtml($_product, true, '-reco-'.$this->getEndpoint()) ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif ?>